

var MW = MW || {};

MW.SCREEN = {
    WIDTH: 577,
    HEIGHT: 432
}
MW.SCROLL_SPEED = 1
MW.GROUND = 32
MW.BIRD = {
    WIDTH: 32,
    HEIGHT: 24
}
//
MW.DELAY_END_TIME = 1000
// pipe config
MW.MIN_GAP = 150
MW.MAX_GAP = 200
MW.MIN_HEIGHT = 100
MW.PIPE_MOVEBY_X = -3
MW.PIPE_MOVEBY_TIME = 0.0004
// bird config
MW.DOWN_SPEED = 2
MW.UP_SPEED = 40
// sound
MW.SOUND = 0
// keyboard
MW.KEYBOARD = {
    ENTER: 13,
    A: 65,
    S: 83,
    D: 68,
}
// Dash skill
MW.DS_BG_SCROLL_SPEED = 10
MW.DS_PIPE_MOVEBY_TIME = 0.00003
MW.DS_USING_TIME = 3
MW.DS_COUNT_DOWN = 11
// Power skill
MW.PS_USING_TIME = 5
MW.PS_COUNT_DOWN = 31